# Generated by Django 2.2.6 on 2019-10-24 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(default='')),
                ('data_criada', models.DateTimeField(default=django.utils.timezone.now)),
                ('numeroLikes', models.IntegerField(default=0)),
                ('numeroComentarios', models.IntegerField(default=0)),
                ('numeroRts', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Curtida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtida', to='api.Postagem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtiu', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Compartilhamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartilhado', to='api.Postagem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartilhou', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(default='')),
                ('data_criada', models.DateTimeField(default=django.utils.timezone.now)),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentado', to='api.Postagem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentou', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
